kind: pipeline
name: upload

trigger:
  event:
    - tag

workspace:
  base: /src
  path: chart/${DRONE_REPO_NAME}

steps:
  - name: package
    image: alpine/helm:3.1.1
    command: helm package ./osrm -d packaged-chart

  - name: upload
    image: amazon/aws-cli:2.4.18
    command: aws s3 cp packaged-chart/osrm-${DRONE_TAG}.tgz s3://shipt-k8s-helm-charts/osrm-${DRONE_TAG}.tgz