kind: pipeline
name: test-workload
trigger:
  event:
    - push
    - tag
  branch:
    include:
      - main

steps:
  - name: publish-helm-chart
    image: pkg.harness.io/p7nidaektwegp3qiqixe1a/devops/chart-publisher:latest
    when:
      event:
        include:
          - tag
    settings:
      harness_user:
        from_secret: HARNESS_DRONE_USER
      harness_password:
        from_secret: HARNESS_DRONE_PASS
      harness_url: pkg.harness.io/p7nidaektwegp3qiqixe1a
      chart_path: osrm