apiVersion: v1
kind: Service
metadata:
  name: {{ include "osrm.fullname" . }}
  namespace: osrm
  labels:
{{ include "osrm.labels" . | indent 4 }}
  annotations:
    projectcontour.io/max-connections: {{ .Values.httpproxy.max_connections  }}
    projectcontour.io/max-requests: {{ .Values.httpproxy.max_requests }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "osrm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
