apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "osrm.fullname" . }}
  namespace: {{ include "osrm.namespace" . }}
  annotations:
    iam.gke.io/gcp-service-account: {{ $.Values.serviceAccountEmail }}
  labels:
    app.kubernetes.io/name: {{ include "osrm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}