apiVersion: v1
kind: Service
metadata:
  name: {{ include "osrm.fullname" . }}-headless
  labels:
{{ include "osrm.labels" . | indent 4 }}
  namespace: osrm
spec:
  type: {{ .Values.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "osrm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
