apiVersion: v1
kind: ServiceAccount
metadata:
  name: osrm
  namespace: osrm
  annotations:
    iam.gke.io/gcp-service-account: {{ $.Values.serviceAccountEmail }}
  labels:
    app.kubernetes.io/name: {{ include "osrm.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}